import { Stack, Typography, Card, Box, Grid } from '@mui/material'

function Home() {
  return (
    <div
      style={{
        marginTop: '5%',
        marginBottom: '5%',
        marginLeft: '10%',
        marginRight: '10%',
      }}
    >
      <Grid
        container
        spacing={0}
        direction="row"
        justifyContent="center"
        style={{}}
      >
        <Grid item xs={3} sx={{ p: 0, m: 0 }}>
          <img src="https://i.imgur.com/uMoBVbS.png" alt="logo" />
        </Grid>
        <Grid item xs={4} sx={{ p: 0, m: 0 }}>
          <Typography
            align="center"
            sx={{
              fontFamily: 'Righteous',
              fontWeight: 300,
              fontSize: 70,
              color: 'black',
              textDecoration: 'none',
              mr: 3,
            }}
          >
            TeaLink
          </Typography>
        </Grid>
      </Grid>
      <Box sx={{ width: '100%' }}>
        <Box>
          <Stack>
            <img
              src="https://i.imgur.com/uMoBVbS.png"
              alt="logo"
              style={{
                height: '12%',
                width: '8%',
              }}
            />
            <Typography
              align="center"
              sx={{
                fontFamily: 'Righteous',
                fontWeight: 300,
                fontSize: 70,
                color: 'black',
                textDecoration: 'none',
                mr: 3,
              }}
            >
              TeaLink
            </Typography>
          </Stack>
        </Box>

        <Card style={{ width: '100%' }}>
          <Typography style={{ fontSize: 12 }}>
            Welcome to TeaLink, the first open-ended peer-to-peer news betting
            protocol on the Ethereum network. TeaLink provides a platform for
            users to create custom bets on anything and everything, using a
            Chainlink oracle and NewsAPI.org to verify whether or not the
            bet-upon event has occurred by searching for keywords given by the
            bet creator in news headlines.
          </Typography>
          <Typography>
            Here’s how it works: You can create a bet that something will happen
            by selecting keywords or key-phrases that you believe will appear in
            future headlines if the event comes to pass. For example, if you
            think that A$AP Rocky and Rihanna will break up, you might create a
            bet with “Rocky”, “Rihanna”, and “break up” as your keywords. Once
            your bet is created it will be listed on the bet marketplace where
            other users can buy-in to accept it. News API will then query every
            headline generated by relevant outlets for your keywords, and if
            enough headlines containing them are found you will win your TeaLink
            bet! Using our novel headline keyword betting mechanism, TeaLink
            allows users to make bets in both traditional areas, like the
            outcome of sporting events - using for example “Verstappen” + “Wins”
            + “Monaco Grand Prix” as keywords - and in areas that have never
            before been included in organized betting such as celebrity
            relationships, the outcomes of prominent lawsuits, global conflicts,
            etc.
          </Typography>
        </Card>
      </Box>
    </div>
  )
}

export default Home
